# .markdownlint.yml — Markdown linting rules
# Used by both CI (markdownlint-cli2-action) and local (markdownlint-cli2)

default: true

# Allow long lines (dotfiles READMEs often have badge URLs, tables, etc.)
MD013:
  line_length: 300
  heading_line_length: 120
  code_block_line_length: 200
  tables: false

# No multiple consecutive blank lines
MD012:
  maximum: 1

# Allow duplicate headings in different sections
MD024:
  siblings_only: true

# Allow raw HTML (badges, images, comments)
MD033: false

# Allow bare URLs
MD034: false

# Don't enforce first-line heading (we use logo images)
MD041: false
