#!/usr/bin/env zsh

# +----------+
# | PATH XDG |
# +----------+

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath

# +----+
# | GO |
# +----+
export GOPATH="$XDG_CONFIG_HOME/go"
export GOBIN="$XDG_CONFIG_HOME/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"
export PATH="$GOBIN:$PATH"

# +-----+
# | NPM |
# +-----+
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"
export PATH="$NPM_BIN:$PATH"
