#!/usr/bin/env zsh

export LANG=en_CA.UTF-8
export LC_ALL=en_CA.UTF-8
setopt long_list_jobs
export TERM=xterm-256color

# +---------+
# | HISTORY |
# +---------+
export HISTSIZE=1000            # Maximum events for internal history
export SAVEHIST=1000            # Maximum events in history file
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
HIST_STAMPS="yyyymmdd"

# +-------+
# |EDITOR |
# +-------+
export EDITOR="vim"
export VISUAL="vim"

# +---------------------+
# | SYNTAX HIGHLIGHTING |
# +---------------------+
# source $DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# +------+
# | PATH |
# +------+

export PATH="$XDG_CONFIG_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

# +-----------+
# | FUNCTIONS |
# +-----------+
source $ZDOTDIR/functions.zsh

# +---------+
# | ALIASES |
# +---------+
source $ZDOTDIR/aliases.zsh

# +-------+
# |PROMPT |
# +-------+
eval "$(starship init zsh)"
